apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      containers:
      - name: frontend
        image: nguyentannga2001/udagram-frontend:0.1.3
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
        resources:
          requests:
            cpu: 256m
          limits:
            cpu: 512m
