apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: tyhuynh99/udagram-reverseproxy:0.1.14
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 256m
          limits:
            cpu: 512m